# Generated by Django 5.2.6 on 2025-09-07 08:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_lead', 'New Lead Available'), ('lead_assigned', 'Lead Assigned to You'), ('client_response', 'Client Responded'), ('review_received', 'New Review'), ('credit_low', 'Credits Running Low'), ('subscription_expiring', 'Subscription Expiring'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('system_update', 'System Update'), ('payment_received', 'Payment Received'), ('lead_expired', 'Lead Expired')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent_via_sms', models.BooleanField(default=False)),
                ('is_sent_via_email', models.BooleanField(default=False)),
                ('is_sent_via_push', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True, help_text='URL for action button')),
                ('action_text', models.CharField(blank=True, help_text='Text for action button', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('lead_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leadassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
