# Generated by Django 5.2.6 on 2025-09-09 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_hiring_intent_lead_hiring_timeline_and_more'),
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('email_lead_assigned', models.BooleanField(default=True)),
                ('email_quote_received', models.BooleanField(default=True)),
                ('email_quote_response', models.BooleanField(default=True)),
                ('email_credit_purchase', models.BooleanField(default=True)),
                ('email_deposit_verified', models.BooleanField(default=True)),
                ('email_system', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('sms_lead_assigned', models.BooleanField(default=False)),
                ('sms_quote_received', models.BooleanField(default=False)),
                ('sms_urgent_only', models.BooleanField(default=True)),
                ('dashboard_notifications', models.BooleanField(default=True)),
                ('show_popup', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('lead_assigned', 'Lead Assigned'), ('quote_received', 'Quote Received'), ('quote_response', 'Quote Response'), ('credit_purchase', 'Credit Purchase'), ('deposit_verified', 'Deposit Verified'), ('lead_verified', 'Lead Verified'), ('system', 'System Notification'), ('system_update', 'System Update'), ('reminder', 'Reminder')], max_length=50)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('email_template', models.TextField(blank=True)),
                ('sms_template', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_8a7c6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_f2e0f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_priorit_f7c359_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action_text',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_sent_via_email',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_sent_via_push',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_sent_via_sms',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='lead_assignment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='review',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lead_assigned', 'Lead Assigned'), ('quote_received', 'Quote Received'), ('quote_response', 'Quote Response'), ('credit_purchase', 'Credit Purchase'), ('deposit_verified', 'Deposit Verified'), ('lead_verified', 'Lead Verified'), ('system', 'System Notification'), ('system_update', 'System Update'), ('reminder', 'Reminder')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
