#!/bin/bash

echo "🚀 QUICK DEPLOY: Multiple Service Selection Fix"
echo "=============================================="

echo "📋 Manual deployment steps for Hetzner server:"
echo ""
echo "1. SSH into your Hetzner server:"
echo "   ssh root@hetzner.proconnectsa.co.za"
echo ""
echo "2. Run these commands on the server:"
echo ""
echo "   # Navigate to backend directory"
echo "   cd /opt/proconnectsa-backend"
echo ""
echo "   # Pull latest changes"
echo "   git pull origin main"
echo ""
echo "   # Stop Django server"
echo "   pkill -f 'python.*manage.py.*runserver'"
echo ""
echo "   # Start Django server"
echo "   nohup python manage.py runserver 0.0.0.0:8000 > /dev/null 2>&1 &"
echo ""
echo "   # Test the fix"
echo "   sleep 5"
echo "   curl http://localhost:8000/health/"
echo ""
echo "✅ The multiple service selection bug will be fixed!"
echo "🎯 Providers will now receive leads for ALL their selected services."
