#!/usr/bin/env python3
"""
Simple script to update yusuf jack's services using Django shell commands
"""

print("🔧 UPDATING YUSUF JACK'S SERVICES")
print("=" * 50)

print("Run these Django shell commands on the server:")
print("")
print("cd /opt/proconnectsa")
print("source venv/bin/activate")
print("python manage.py shell")
print("")
print("Then run these commands in the Django shell:")
print("")
print("# Import required models")
print("from backend.users.models import User, ProviderProfile")
print("from backend.leads.models import ServiceCategory")
print("from backend.users.services.models import Service")
print("")
print("# Find yusuf jack")
print("user = User.objects.get(first_name__icontains='yusuf', last_name__icontains='jack')")
print("profile = user.provider_profile")
print("")
print("# Get service categories")
print("cleaning_cat = ServiceCategory.objects.get_or_create(slug='cleaning', defaults={'name': 'Cleaning Services', 'is_active': True})[0]")
print("electrical_cat = ServiceCategory.objects.get_or_create(slug='electrical', defaults={'name': 'Electrical', 'is_active': True})[0]")
print("plumbing_cat = ServiceCategory.objects.get_or_create(slug='plumbing', defaults={'name': 'Plumbing', 'is_active': True})[0]")
print("")
print("# Add services")
print("Service.objects.get_or_create(provider=profile, category=electrical_cat, defaults={'name': 'Electrical Services', 'is_active': True})")
print("Service.objects.get_or_create(provider=profile, category=plumbing_cat, defaults={'name': 'Plumbing Services', 'is_active': True})")
print("Service.objects.get_or_create(provider=profile, category=cleaning_cat, defaults={'name': 'Cleaning Services', 'is_active': True})")
print("")
print("# Update service areas")
print("profile.service_areas = ['Cape Town', 'Johannesburg']")
print("")
print("# Sync service categories")
print("active_categories = set()")
print("for service in profile.services.filter(is_active=True):")
print("    if service.category.slug:")
print("        active_categories.add(service.category.slug)")
print("profile.service_categories = list(active_categories)")
print("profile.save()")
print("")
print("# Verify")
print("print('Services:', [s.name for s in profile.services.filter(is_active=True)])")
print("print('Categories:', profile.service_categories)")
print("exit()")
print("")
print("🎉 This will add electrical and plumbing services to yusuf jack!")
