# Generated by Django 5.2.6 on 2025-09-07 08:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Overall rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('quality_rating', models.IntegerField(help_text='Quality of work rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.IntegerField(help_text='Communication quality rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeliness_rating', models.IntegerField(help_text='Timeliness rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('value_rating', models.IntegerField(help_text='Value for money rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('job_completed', models.BooleanField(default=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('would_recommend', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified that job actually happened')),
                ('is_public', models.BooleanField(default=True)),
                ('is_moderated', models.BooleanField(default=False)),
                ('moderation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('lead_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='leads.leadassignment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'is_public', 'created_at'], name='reviews_rev_provide_aa0ae2_idx'), models.Index(fields=['rating', 'is_public'], name='reviews_rev_rating_1e30ef_idx'), models.Index(fields=['is_verified', 'is_public'], name='reviews_rev_is_veri_d62a04_idx')],
            },
        ),
    ]
