# Generated by Django 4.2.7 on 2026-02-14 03:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_add_google_review_model"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="googlereview",
            new_name="reviews_goo_provide_42f882_idx",
            old_name="reviews_goog_provider_idx",
        ),
        migrations.RenameIndex(
            model_name="googlereview",
            new_name="reviews_goo_review__b866a0_idx",
            old_name="reviews_goog_review_s_idx",
        ),
    ]
