# Generated by Django 5.2.6 on 2025-09-07 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Credit Purchase'), ('deduction', 'Lead Assignment'), ('refund', 'Lead Refund'), ('bonus', 'Bonus Credits'), ('subscription', 'Monthly Subscription'), ('admin_adjustment', 'Admin Adjustment'), ('expired_lead', 'Expired Lead Refund')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('amount', models.IntegerField(help_text='Positive for addition, negative for deduction')),
                ('balance_after', models.IntegerField(help_text="Provider's credit balance after this transaction")),
                ('payment_reference', models.CharField(blank=True, help_text='External payment reference (PayPal, Stripe, etc.)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin adjustments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('lead_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadassignment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'created_at'], name='payments_cr_provide_d1893d_idx'), models.Index(fields=['transaction_type', 'created_at'], name='payments_cr_transac_6cb56f_idx'), models.Index(fields=['status', 'created_at'], name='payments_cr_status_429920_idx')],
            },
        ),
    ]
