# Generated by Django 4.2.7 on 2025-09-09 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(help_text='Unique reference number for the deposit', max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be deposited', max_digits=10)),
                ('credits_to_activate', models.IntegerField(help_text='Number of credits to activate after verification')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('deposit_slip', models.URLField(blank=True, help_text='URL to uploaded deposit slip')),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Deposit expires after 7 days if not verified')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_deposits', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference_number'], name='payments_ma_referen_f8c2cc_idx'), models.Index(fields=['status', 'created_at'], name='payments_ma_status_029d05_idx'), models.Index(fields=['expires_at'], name='payments_ma_expires_39a10a_idx')],
            },
        ),
    ]
