# Generated by Django 5.2.6 on 2025-09-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_enhance_transaction_for_ml'),
    ]

    operations = [
    ]
