# Generated by Django 5.2.6 on 2025-09-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_merge_20250911_2202'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_lead_id_861912_idx',
            old_name='transactions_lead_id_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_pricing_1b8fb0_idx',
            old_name='transactions_pricing_method_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_job_com_07b76e_idx',
            old_name='transactions_job_completed_idx',
        ),
    ]
