# Generated by Django 5.2.6 on 2025-09-14 10:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_support_staff_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportmetrics',
            options={'ordering': ['-date'], 'verbose_name': 'Support Metrics', 'verbose_name_plural': 'Support Metrics'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Support Ticket', 'verbose_name_plural': 'Support Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketresponse',
            options={'ordering': ['created_at'], 'verbose_name': 'Ticket Response', 'verbose_name_plural': 'Ticket Responses'},
        ),
        migrations.AlterModelOptions(
            name='tickettemplate',
            options={'verbose_name': 'Ticket Template', 'verbose_name_plural': 'Ticket Templates'},
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='support_sup_status_c67c70_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='support_sup_categor_a1e5a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='support_sup_user_id_2e68d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='support_sup_assigne_87974a_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketresponse',
            name='support_tic_ticket__9566a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketresponse',
            name='support_tic_author__42ece0_idx',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='ticketresponse',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='ticketresponse',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='variables',
            field=models.JSONField(blank=True, default=list, help_text='Available template variables'),
        ),
        migrations.AlterField(
            model_name='supportmetrics',
            name='avg_resolution_time',
            field=models.FloatField(default=0.0, help_text='Average resolution time in hours'),
        ),
        migrations.AlterField(
            model_name='supportmetrics',
            name='open_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supportmetrics',
            name='resolved_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supportmetrics',
            name='total_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='satisfaction_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='response_type',
            field=models.CharField(choices=[('customer', 'Customer Response'), ('staff', 'Staff Response'), ('system', 'System Response')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='category',
            field=models.CharField(choices=[('general_responses', 'General Responses'), ('technical_responses', 'Technical Responses'), ('billing_responses', 'Billing Responses'), ('account_responses', 'Account Responses')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='subject_template',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
