# Generated by Django 5.2.6 on 2025-09-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_supportmetrics_options_and_more'),
    ]

    operations = [
    ]
