# Generated by Django 4.2.7 on 2025-09-19 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('id_type', models.CharField(choices=[('sa_id', 'South African ID'), ('passport', 'Passport')], max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='business_registrations/id_documents/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('pty_ltd', 'Private Company (Pty Ltd)'), ('public_ltd', 'Public Company (Ltd)'), ('cc', 'Close Corporation (CC)'), ('sole_prop', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('npc', 'Non-Profit Company (NPC)'), ('inc', 'Personal Liability Company (Inc)')], max_length=20)),
                ('business_category', models.CharField(max_length=100)),
                ('business_description', models.TextField()),
                ('street_address', models.CharField(max_length=200)),
                ('suburb', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('website_required', models.BooleanField(default=True)),
                ('website_type', models.CharField(blank=True, max_length=200, null=True)),
                ('website_features', models.JSONField(blank=True, default=list)),
                ('domain_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_urgency', models.CharField(choices=[('standard', 'Standard (7-14 days) - R1,350'), ('express', 'Express (3-7 days) - R1,850'), ('rush', 'Rush (1-3 days) - R2,350')], max_length=20)),
                ('preferred_start_date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_reference', models.CharField(max_length=50)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_received', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_received', 'Payment Received'), ('documents_review', 'Documents Under Review'), ('cipc_submission', 'CIPC Submission in Progress'), ('website_development', 'Website Development'), ('completed', 'Registration Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_registrations',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessRegistrationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('business_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_notes', to='business.businessregistration')),
            ],
            options={
                'db_table': 'business_registration_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('id_type', models.CharField(choices=[('sa_id', 'South African ID'), ('passport', 'Passport')], max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='business_registrations/director_documents/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('shareholding', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='business.businessregistration')),
            ],
            options={
                'db_table': 'business_directors',
            },
        ),
    ]
