# Generated by Django 4.2.7 on 2025-09-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='business_name_alternative',
            field=models.CharField(default='', help_text='Second choice business name', max_length=200),
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='business_name',
            field=models.CharField(help_text='First choice business name', max_length=200),
        ),
    ]
