# Generated by Django 4.2.7 on 2025-09-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='hiring_intent',
            field=models.CharField(blank=True, choices=[('ready_to_hire', 'Ready to Hire'), ('planning_to_hire', 'Planning to Hire Soon'), ('researching', 'Just Researching/Exploring'), ('comparing_quotes', 'Comparing Quotes')], help_text="Client's hiring intent and readiness", max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='hiring_timeline',
            field=models.CharField(blank=True, choices=[('asap', 'ASAP (within 1 week)'), ('this_month', 'This Month'), ('next_month', 'Next Month'), ('flexible', 'Flexible Timing')], help_text='When client plans to start the project', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='research_purpose',
            field=models.TextField(blank=True, help_text='Additional context about project goals and requirements'),
        ),
    ]
