# Generated by Django 5.2.6 on 2025-09-09 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_hiring_intent_lead_hiring_timeline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_type', models.CharField(choices=[('quality', 'Lead Quality'), ('conversion', 'Conversion Probability'), ('pricing', 'Dynamic Pricing')], max_length=20)),
                ('model_version', models.CharField(max_length=50)),
                ('input_summary', models.JSONField(blank=True, default=dict)),
                ('output_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prediction_type', 'created_at'], name='leads_predi_predict_f7b87b_idx'), models.Index(fields=['model_version'], name='leads_predi_model_v_0cd5e7_idx')],
            },
        ),
    ]
