# Generated by Django 5.2.6 on 2025-09-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_predictionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadassignment',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('viewed', 'Viewed by Provider'), ('purchased', 'Purchased by Provider'), ('contacted', 'Provider Contacted Client'), ('quoted', 'Quote Provided'), ('won', 'Job Won'), ('lost', 'Job Lost'), ('no_response', 'No Response from Provider')], default='assigned', max_length=20),
        ),
    ]
