# Generated by Django 5.2.6 on 2025-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadassignment_purchased_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ab_test_groups',
            },
        ),
        migrations.CreateModel(
            name='ABTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('event_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ab_test_results',
            },
        ),
        migrations.AddConstraint(
            model_name='abtestgroup',
            constraint=models.UniqueConstraint(fields=('user_id', 'test_name'), name='unique_user_test'),
        ),
        migrations.AddIndex(
            model_name='abtestresult',
            index=models.Index(fields=['test_name', 'group', 'event_type'], name='ab_test_results_test_group_event_idx'),
        ),
        migrations.AddIndex(
            model_name='abtestresult',
            index=models.Index(fields=['user_id', 'test_name'], name='ab_test_results_user_test_idx'),
        ),
        migrations.AddIndex(
            model_name='abtestresult',
            index=models.Index(fields=['created_at'], name='ab_test_results_created_at_idx'),
        ),
    ]
