# Generated by Django 5.2.6 on 2025-09-12 02:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_add_bark_style_lead_flow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('credit_cost', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.DeleteModel(
            name='MLFeatureImportance',
        ),
        migrations.DeleteModel(
            name='MLModelPerformance',
        ),
        migrations.DeleteModel(
            name='MLModelTrainingLog',
        ),
        migrations.DeleteModel(
            name='MLPredictionLog',
        ),
        migrations.RemoveConstraint(
            model_name='abtestgroup',
            name='unique_user_test',
        ),
        migrations.RenameIndex(
            model_name='abtestresult',
            new_name='ab_test_res_test_na_2c67c3_idx',
            old_name='ab_test_results_test_group_event_idx',
        ),
        migrations.RenameIndex(
            model_name='abtestresult',
            new_name='ab_test_res_user_id_9c9b83_idx',
            old_name='ab_test_results_user_test_idx',
        ),
        migrations.RenameIndex(
            model_name='abtestresult',
            new_name='ab_test_res_created_69c570_idx',
            old_name='ab_test_results_created_at_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='credit_cost',
        ),
        migrations.AlterField(
            model_name='lead',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When the lead was fully claimed (all slots filled)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='abtestgroup',
            unique_together={('user_id', 'test_name')},
        ),
        migrations.AddField(
            model_name='leadaccess',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadaccess',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='leadaccess',
            unique_together={('lead', 'provider')},
        ),
    ]
