# Generated by Django 4.2.7 on 2025-09-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_add_bark_competition_stats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-verification_score', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_service_ee1899_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_verific_6436ec_idx',
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'service_category_id'], name='leads_lead_status_af52f3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['location_city', 'status'], name='leads_lead_locatio_b9e7f0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['verification_score', 'created_at'], name='leads_lead_verific_2268ea_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['service_category_id', 'location_city'], name='leads_lead_service_ee1899_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_available', 'status'], name='leads_lead_is_avai_803ea9_idx'),
        ),
    ]
