# Generated by Django 4.2.7 on 2025-09-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_add_credit_cost_to_lead'),
        ('leads', '0010_add_enterprise_indexes'),
    ]

    operations = [
    ]
