# Generated by Django 4.2.7 on 2025-09-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_merge_20250929_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='property_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial/Office'), ('industrial', 'Industrial'), ('retail', 'Retail'), ('other', 'Other')], help_text='Type of property where work will be performed', max_length=20),
        ),
    ]
