# Generated by Django 4.2.7 on 2026-04-13 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0006_rename_transactions_lead_id_idx_transaction_lead_id_861912_idx_and_more'),
        ('leads', '0016_lead_providers_routed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits_required', models.IntegerField(default=1)),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Rands due for this reservation', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Deposit reference number', max_length=100)),
                ('expires_at', models.DateTimeField(help_text='Reservation expiry timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_provid_6c8f9e_idx',
        ),
        migrations.AlterField(
            model_name='lead',
            name='providers_routed_at',
            field=models.DateTimeField(blank=True, help_text='When this lead was first routed to providers (assignment + notifications); prevents duplicate sends.', null=True),
        ),
        migrations.AddField(
            model_name='leadreservation',
            name='deposit_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_reservations', to='payments.depositrequest'),
        ),
        migrations.AddField(
            model_name='leadreservation',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadreservation',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leadreservation',
            index=models.Index(fields=['provider', 'created_at'], name='leads_leadr_provide_ac4c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='leadreservation',
            index=models.Index(fields=['lead', 'status'], name='leads_leadr_lead_id_1c865e_idx'),
        ),
        migrations.AddIndex(
            model_name='leadreservation',
            index=models.Index(fields=['status', 'expires_at'], name='leads_leadr_status_4325d3_idx'),
        ),
    ]
