# Generated by Django 4.2.7 on 2025-09-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='service_categories',
            field=models.JSONField(default=list, help_text="List of service category slugs: ['plumbing', 'electrical']"),
        ),
    ]
