# Generated by Django 5.2.6 on 2025-09-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_providerprofile_service_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='monthly_lead_limit',
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('basic', 'Basic - R250/month'), ('advanced', 'Advanced - R450/month'), ('pro', 'Pro - R650/month'), ('enterprise', 'Enterprise - R850/month')], default='basic', max_length=20),
        ),
    ]
