# Generated by Django 5.2.6 on 2025-09-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_providerprofile_monthly_lead_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='customer_code',
            field=models.CharField(blank=True, help_text='Unique customer code for automatic deposit processing', max_length=10, null=True, unique=True),
        ),
    ]
