# Generated by Django 5.2.6 on 2025-09-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_providerprofile_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('pay_as_you_go', 'Pay-as-You-Go - R80 per lead'), ('basic', 'Basic - R250/month (5 leads)'), ('advanced', 'Advanced - R450/month (12 leads)'), ('pro', 'Pro - R650/month (24 leads)'), ('enterprise', 'Enterprise - R850/month (unlimited)')], default='pay_as_you_go', max_length=20),
        ),
    ]
