# Generated by Django 5.2.6 on 2025-09-14 06:18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_leadaccess_delete_mlfeatureimportance_and_more'),
        ('users', '0009_fix_leadclaim_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=50)),
                ('credits_spent', models.PositiveIntegerField()),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('full_contact_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credits', models.PositiveIntegerField(default=0)),
                ('customer_code', models.CharField(help_text='Unique code for bank deposit reference', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('unlock', 'Lead Unlock'), ('refund', 'Refund'), ('bonus', 'Bonus Credits')], max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('lead_id', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_title', models.CharField(blank=True, max_length=200)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Job Categories'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='leadclaim',
            options={'ordering': ['-claimed_at']},
        ),
        migrations.AlterModelOptions(
            name='mlpricingfactor',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='users_lead_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='users_lead_category_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='users_lead_status_0a73d0_idx',
            old_name='users_lead_status_idx',
        ),
        migrations.AddField(
            model_name='mlpricingfactor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='leadclaim',
            name='payment_method',
            field=models.CharField(choices=[('allocation', 'Monthly Allocation'), ('topup', 'Credit Top-up'), ('payasyougo', 'Pay-as-You-Go')], default='payasyougo', max_length=20),
        ),
        migrations.AlterField(
            model_name='mlpricingfactor',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.jobcategory'),
        ),
        migrations.AlterField(
            model_name='mlpricingfactor',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mlpricingfactor',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mlpricingfactor',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (6-12)'), ('afternoon', 'Afternoon (12-17)'), ('evening', 'Evening (17-21)'), ('night', 'Night (21-6)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mlpricingfactor',
            name='urgency',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('pay_as_you_go', 'Pay-as-You-Go - R50 per lead'), ('basic', 'Basic - R299/month (5 leads)'), ('advanced', 'Advanced - R599/month (12 leads)'), ('pro', 'Pro - R999/month (30 leads)'), ('enterprise', 'Enterprise - R1,000/month (50 leads)')], default='pay_as_you_go', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['category', 'location'], name='users_lead_categor_e6e6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['urgency', 'created_at'], name='users_lead_urgency_e861d9_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['expires_at'], name='users_lead_expires_9f446d_idx'),
        ),
        migrations.AddIndex(
            model_name='leadclaim',
            index=models.Index(fields=['provider', 'claimed_at'], name='users_leadc_provide_7c77b9_idx'),
        ),
        migrations.AddIndex(
            model_name='leadclaim',
            index=models.Index(fields=['lead', 'claimed_at'], name='users_leadc_lead_id_bec075_idx'),
        ),
        migrations.AddIndex(
            model_name='mlpricingfactor',
            index=models.Index(fields=['category', 'location'], name='users_mlpri_categor_4f807c_idx'),
        ),
        migrations.AddIndex(
            model_name='mlpricingfactor',
            index=models.Index(fields=['urgency', 'time_of_day'], name='users_mlpri_urgency_ccdf93_idx'),
        ),
        migrations.AddField(
            model_name='leadunlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.wallet'),
        ),
        migrations.AddField(
            model_name='leadunlock',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_unlocks', to='users.wallettransaction'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference'], name='users_walle_referen_9df1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='users_walle_wallet__7a1893_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status', 'transaction_type'], name='users_walle_status_6ef58f_idx'),
        ),
        migrations.AddIndex(
            model_name='leadunlock',
            index=models.Index(fields=['user', 'lead_id'], name='users_leadu_user_id_32b657_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadunlock',
            unique_together={('user', 'lead_id')},
        ),
    ]
