# Generated by Django 5.2.6 on 2025-09-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_leadaccess_delete_mlfeatureimportance_and_more'),
        ('users', '0011_add_dashboard_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticketresponse',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketresponse',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='leadpurchase',
            name='unique_user_lead_purchase',
        ),
        migrations.AlterUniqueTogether(
            name='leadpurchase',
            unique_together={('user', 'lead')},
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
        migrations.DeleteModel(
            name='TicketResponse',
        ),
    ]
