# Generated by Django 5.2.6 on 2025-09-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_duplicate_support_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='ml_follow_through_score',
            field=models.FloatField(default=0.0, help_text='ML-predicted follow-through score (0-100)'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='ml_last_updated',
            field=models.DateTimeField(blank=True, help_text='When ML scores were last updated', null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='ml_quality_score',
            field=models.FloatField(default=0.0, help_text='ML-predicted quality score (0-100)'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='ml_risk_score',
            field=models.FloatField(default=0.0, help_text='ML-predicted risk score (0-100)'),
        ),
    ]
