# Generated by Django 4.2.7 on 2025-09-17 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_providerprofile_ml_follow_through_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='South African phone number in format +27XXXXXXXXX', max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+27812345678'", regex='^\\+27\\d{9}$')]),
        ),
    ]
