# Generated by Django 4.2.7 on 2026-03-31 05:16
# Database ops are conditional: production may already have premium columns from manual / partial deploy.

from django.db import migrations, models


def _existing_columns(schema_editor, table: str) -> set:
    conn = schema_editor.connection
    with conn.cursor() as cur:
        if conn.vendor == "postgresql":
            cur.execute(
                """
                SELECT column_name FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = %s
                """,
                [table],
            )
            return {r[0] for r in cur.fetchall()}
        if conn.vendor == "sqlite":
            cur.execute(f"PRAGMA table_info({table})")
            return {r[1] for r in cur.fetchall()}
    return set()


def ensure_premium_columns_forwards(apps, schema_editor):
    ProviderProfile = apps.get_model("users", "ProviderProfile")
    table = ProviderProfile._meta.db_table
    cols = _existing_columns(schema_editor, table)
    conn = schema_editor.connection
    with conn.cursor() as cur:
        if "is_premium_listing" not in cols:
            if conn.vendor == "postgresql":
                cur.execute(
                    f"ALTER TABLE {table} ADD COLUMN is_premium_listing boolean DEFAULT false NOT NULL"
                )
            else:
                cur.execute(
                    f"ALTER TABLE {table} ADD COLUMN is_premium_listing bool NOT NULL DEFAULT 0"
                )
        if "premium_listing_expires_at" not in cols:
            cur.execute(
                f"ALTER TABLE {table} ADD COLUMN premium_listing_expires_at timestamp with time zone NULL"
                if conn.vendor == "postgresql"
                else f"ALTER TABLE {table} ADD COLUMN premium_listing_expires_at datetime NULL"
            )
        if "premium_listing_payment_reference" not in cols:
            cur.execute(
                f"ALTER TABLE {table} ADD COLUMN premium_listing_payment_reference varchar(100) NOT NULL DEFAULT ''"
            )
        if "premium_listing_started_at" not in cols:
            cur.execute(
                f"ALTER TABLE {table} ADD COLUMN premium_listing_started_at timestamp with time zone NULL"
                if conn.vendor == "postgresql"
                else f"ALTER TABLE {table} ADD COLUMN premium_listing_started_at datetime NULL"
            )


def ensure_premium_columns_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_providerprofile_pro_welcome_email_sent_at"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    ensure_premium_columns_forwards,
                    ensure_premium_columns_reverse,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="providerprofile",
                    name="is_premium_listing",
                    field=models.BooleanField(
                        default=False,
                        help_text="Provider has paid for premium listing in public directory",
                    ),
                ),
                migrations.AddField(
                    model_name="providerprofile",
                    name="premium_listing_expires_at",
                    field=models.DateTimeField(
                        blank=True,
                        help_text="When premium listing expires (null = lifetime)",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="providerprofile",
                    name="premium_listing_payment_reference",
                    field=models.CharField(
                        blank=True,
                        help_text="EFT reference number for premium listing payment",
                        max_length=100,
                    ),
                ),
                migrations.AddField(
                    model_name="providerprofile",
                    name="premium_listing_started_at",
                    field=models.DateTimeField(
                        blank=True,
                        help_text="When premium listing was activated",
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="user",
                    name="user_type",
                    field=models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("provider", "Service Provider"),
                            ("admin", "Administrator"),
                            ("support", "Support Team"),
                        ],
                        default="client",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
